language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  pytest --cov
after_success:
  coveralls

notifications:
  irc: "irc.quakenet.org#xanmel"
