language: python
python:
  - "3.8"
  - "3.9"

install:
  - python setup.py develop
  - pip install -r requirements-test.txt

script:
  pytest --cov
after_success:
  coveralls

notifications:
  irc: "irc.quakenet.org#xanmel"
