xanmel.modules.irc.IRCModule:
  host: irc.quakenet.org
  port: 6667
  ssl: false
  nick: xanmel
  realname: Xanmel BOT
  channel: '#xanmel'
  greeting: HELLO WORLD!
  mention_delimeters: [' ', ':', ',']
xanmel.modules.xonotic.XonoticModule:
  server_ip: 127.0.0.1
  server_port: 26005
