xanmel.modules.irc.IRCModule:
  host: irc.quakenet.org
  port: 6667
  ssl: false
  nick: xanmel
  realname: Xanmel BOT
  channel: '#xanmel'
  greeting: HELLO WORLD!
  mention_delimeters: [' ', ':', ',']
xanmel.modules.xonotic.XonoticModule:
  servers:
    - rcon_ip: 127.0.0.1
      rcon_port: 26005
      public_ip: 99.99.99.99
      public_port: 26005
      rcon_password: password
