what_happened = [
    'your aim was off because of',
    'you were an easy target because of',
    "you couldn't hit shit because of",
    "the reason of your misfortunes was the",
    "you couldn't do better due to",
]

excuses = [
    "clock speed",
    "solar flares",
    "electromagnetic radiation from satellite debris",
    "static from nylon underwear",
    "static from plastic slide rules",
    "global warming",
    "poor power conditioning",
    "static buildup",
    "doppler effect",
    "hardware stress fractures",
    "magnetic interference from money/credit cards",
    "dry joints on cable plug",
    "temporary routing anomaly",
    "somebody who was calculating pi on the server",
    "fat electrons in the lines",
    "excess surge protection",
    "floating point processor overflow",
    "divide-by-zero error",
    "POSIX compliance problem",
    "your monitor resolution too high",
    "improperly oriented keyboard",
    "network packets travelling uphill (use a carrier pigeon)",
    "decreasing electron flux",
    "first Saturday after first full moon in Winter",
    "radiosity depletion",
    "CPU radiator broken",
    "positron router malfunction",
    "cellular telephone interference",
    "techtonic stress",
    "piezo-electric interference",
    "dynamic software linking table corrupted",
    "heavy gravity fluctuation, move computer to floor rapidly",
    "hairdryer plugged into UPS",
    "terrorist activities",
    "not enough memory",
    "interrupt configuration error",
    "spaghetti cable causing packet failure",
    "bank holiday - system operating credits not recharged",
    "virus attack, luser responsible",
    "waste water tank overflowed onto computer",
    "complete Transient Lockout",
    "bad ether in the cables",
    "bogon emissions",
    "change in Earth's rotational speed",
    "cosmic ray particles crashed through the hard disk platter",
    "smell from unhygienic janitorial staff which wrecked the tape heads",
    "plumber who mistook routing panel for decorative wall fixture",
    "electricians which made popcorn in the power supply",
    "high pressure system failure",
    "computer not properly grounded",
    "CPU recalibration needed",
    "system reboot required",
    "bit bucket overflow",
    "descramble code needed from software company",
    "knot in cables caused data stream to become twisted and kinked",
    "nesting roaches shorted out the ether cable",
    "you're out of memory",
    "unoptimized hard drive",
    "Windows 95 undocumented \"feature\"",
    "runt packets",
    "electromagnetic energy loss",
    "budget cuts",
    "mouse chewed through power cable",
    "stale file handle (next time use Tupperware(tm)!)",
    "internet outage",
    "Pentium FDIV bug",
    "small animal kamikaze attack on power supplies",
    "SIMM crosstalk",
    "IRQ dropout",
    "collapsed backbone",
    "power company testing new voltage spike (creation) equipment",
    "network operators on strike due to broken coffee machine",
    "UPS interrupted the server's power",
    "the electrician who didn't know what the yellow cable was so he yanked the ethernet out",
    "the air conditioning water supply pipe ruptured over the machine room",
    "the rolling stones concert down the road which caused a brown out",
    "the monitor plugged into the serial port",
    "root nameservers out of sync",
    "electro-magnetic pulses from French above ground nuke testing",
    "your keyboard's space bar generating spurious keycodes",
    "the real ttys becoming pseudo ttys and vice-versa",
    "the printer thinking its a router",
    "the router thinking its a printer",
    "evil hackers from Russia",
    "sticky bits on disk",
    "power company having EMP problems with their reactor",
    "the ring needing another token",
    "SCSI Chain overterminated",
    "because of network lag due to too many people playing deathmatch",
    "user distributing pornography on server",
    "disks spinning backwards",
    "too few computrons available",
    "the military using communications satellite for star wars",
    "dew on the telephone lines",
    "big to little endian conversion error",
    "zombie processes haunting the computer",
    "incorrect time synchronization",
    "defunct processes",
    "stubborn processes",
    "non-redundant fan failure",
    "bugs in the RAID",
    "no \"any\" key on keyboard",
    "backbone scoliosis",
    "excessive collisions & not enough packet ambulances",
    "broadcast packets on wrong frequency",
    "recursive traversal of loopback mount points",
    "OS swapped to disk",
    "ether leak",
    "endothermal recalibration",
    "loop found in loop in redundant loopback",
    "runaway cat on system",
    "curls in your keyboard cord losing electricity",
    "quantum dynamics affecting the transistors",
    "police examining all internet packets in the search for a narco-net-trafficker",
    "lightning strikes",
    "fluorescent lights generating negative ions",
    "high nuclear activity in your area",
    "someone thinking The Big Red Button was a light switch",
    "a star wars satellite accidently blowing up the WAN",
    "wrong polarity of neutron flow",
    "ionization from the air-conditioning",
    "TCP/IP UDP alarm threshold too low",
    "someone broadcasting pygmy packets and the router doesn't know how to deal with them",
    "lightning storm you had yesterday",
    "lightning storm you had last week",
    "lightning storm you had last month",
    "too much radiation coming from the soil",
    "processes running slowly due to weak power supply",
    "your ISP having switching problems",
    "your ISP having routing problems",
    "interference from lunar radiation",
    "your /dev/null is being upgraded",
    "neutrino overload on the nameserver",
    "hard drives melting",
    "U.S. Postal Service",
    "electrons on a bender",
    "interference between the keyboard and the chair",
    "too many interrupts",
    "not enough interrupts",
    # "The data on your hard drive is out of balance",
    # "Digital Manipulator exceeding velocity parameters",
    # "appears to be a Slow/Narrow SCSI-0 Interface problem",
    # "microelectronic Riemannian curved-space fault in write-only file system",
    # "fractal radiation jamming the backbone",
    # "routing problems on the neural net",
    # "IRQ-problems with the Un-Interruptible-Power-Supply",
    # "CPU-angle has to be adjusted because of vibrations coming from the nearby road",
    # "emissions from GSM-phones",
    # "CD-ROM server needs recalibration",
    # "firewall needs cooling",
    # "asynchronous inode failure",
    # "transient bus protocol violation",
    # "incompatible bit-registration operators",
    # "your process is not ISO 9000 compliant",
    # "You need to upgrade your VESA local bus to a MasterCard local bus",
    # "The recent proliferation of Nuclear Testing",
    # "Elves on strike. (Why do they call EMAG Elf Magic)",
    # "Internet exceeded Luser level, please wait until a luser logs off before attempting to log back on",
    # "Your EMAIL is now being delivered by the USPS",
    # "Your computer hasn't been returning all the bits it gets from the Internet",
    # "You've been infected by the Telescoping Hubble virus",
    # "Scheduled global CPU outage",
    # "Your Pentium has a heating problem - try cooling it with ice cold water.(Do not turn off your computer, you do not want to cool down the Pentium Chip while he isn't working, do you?)",
    # "Your processor has processed too many instructions.  Turn it off immediately, do not type any commands!!",
    # "Your packets were eaten by the terminator",
    # "Your processor does not develop enough heat",
    # "We need a licensed electrician to replace the light bulbs in the computer room",
    # "The POP server is out of Coke",
    # "Fiber optics caused gas main leak",
    # "Server depressed, needs Prozac",
    # "quantum decoherence",
    # "those damn raccoons!",
    # "suboptimal routing experience",
    # "A plumber is needed, the network drain is clogged",
    # "50% of the manual is in .pdf readme files",
    # "the AA battery in the wallclock sends magnetic interference",
    # "the xy axis in the trackball is coordinated with the summer solstice",
    # "the butane lighter causes the pincushioning",
    # "old inkjet cartridges emanate barium-based fumes",
    # "manager in the cable duct",
    # "We'll fix that in the next (upgrade, update, patch release, service pack)",
    # "HTTPD Error 666 : BOFH was here",
    # "HTTPD Error 4004 : very old Intel cpu - insufficient processing power",
    # "The ATM board has run out of 10 pound notes.  We are having a whip round to refill it, care to contribute ?",
    # "Network failure -  call NBC",
    # "Having to manually track the satellite",
    # "Your/our computer(s) had suffered a memory leak, and we are waiting for them to be topped up",
    # "The rubber band broke",
    # "We're on Token Ring, and it looks like the token got loose",
    # "Stray Alpha Particles from memory packaging caused Hard Memory Error on Server",
    # "paradigm shift...without a clutch",
    # "PEBKAC (Problem Exists Between Keyboard And Chair)",
    # "The cables are not the same length",
    # "Second-system effect",
    # "Chewing gum on /dev/sd3c",
    # "Boredom in the Kernel",
    # "the daemons! the daemons! the terrible daemons!",
    # "I'd love to help you -- it's just that the Boss won't let me near the computer. ",
    # "struck by the Good Times virus",
    # "YOU HAVE AN I/O ERROR -> Incompetent Operator error",
    # "Your parity check is overdrawn and you're out of cache",
    # "Communist revolutionaries taking over the server room and demanding all the computers in the building or they shoot the sysadmin. Poor misguided fools",
    # "Plasma conduit breach",
    # "Out of cards on drive D:",
    # "Sand fleas eating the Internet cables",
    # "parallel processors running perpendicular today",
    # "ATM cell has no roaming feature turned on, notebooks can't connect",
    # "Webmasters kidnapped by evil cult",
    # "Failure to adjust for daylight savings time",
    # "Virus transmitted from computer to sysadmins",
    # "Virus due to computers having unsafe sex",
    # "Incorrectly configured static routes on the corerouters",
    # "Forced to support NT servers; sysadmins quit",
    # "Suspicious pointer corrupted virtual machine",
    # "It's the InterNIC's fault",
    # "Root name servers corrupted",
    # "Budget cuts forced us to sell all the power cords for the servers",
    # "Someone hooked the twisted pair wires into the answering machine",
    # "Operators killed by year 2000 bug bite",
    # "We've picked COBOL as the language of choice",
    # "Operators killed when huge stack of backup tapes fell over",
    # "Robotic tape changer mistook operator's tie for a backup tape",
    # "Someone was smoking in the computer room and set off the halon systems",
    # "Your processor has taken a ride to Heaven's Gate on the UFO behind Hale-Bopp's comet",
    # "it's an ID-10-T error",
    # "Dyslexics retyping hosts file on servers",
    # "The Internet is being scanned for viruses",
    # "Your computer's union contract is set to expire at midnight",
    # "Bad user karma",
    # "/dev/clue was linked to /dev/null",
    # "Increased sunspot activity",
    # "We already sent around a notice about that",
    # "It's union rules. There's nothing we can do about it. Sorry",
    # "Interference from the Van Allen Belt",
    # "Jupiter is aligned with Mars",
    # "Redundant ACLs. ",
    # "Mail server hit by UniSpammer",
    # "T-1's congested due to porn traffic to the news server",
    # "Data for intranet got routed through the extranet and landed on the internet",
    # "We are a 100% Microsoft Shop",
    # "We are Microsoft.  What you are experiencing is not a problem; it is an undocumented feature",
    # "Sales staff sold a product we don't offer",
    # "Secretary sent chain letter to all 5000 employees",
    # "Sysadmin didn't hear pager go off due to loud music from bar-room speakers",
    # "Sysadmin accidentally destroyed pager with a large hammer",
    # "Sysadmins unavailable because they are in a meeting talking about why they are unavailable so much",
    # "Bad cafeteria food landed all the sysadmins in the hospital",
    # "Route flapping at the NAP",
    # "Computers under water due to SYN flooding",
    # "The vulcan-death-grip ping has been applied",
    # "Electrical conduits in machine room are melting",
    # "Traffic jam on the Information Superhighway",
    # "Radial Telemetry Infiltration",
    # "Cow-tippers tipped a cow onto the server",
    # "tachyon emissions overloading the system",
    # "Maintenance window broken",
    # "We're out of slots on the server",
    # "Computer room being moved.  Our systems are down for the weekend",
    # "Sysadmins busy fighting SPAM",
    # "Repeated reboots of the system failed to solve problem",
    # "Feature was not beta tested",
    # "Domain controller not responding",
    # "Someone else stole your IP address, call the Internet detectives!",
    # "It's not RFC-822 compliant",
    # "operation failed because: there is no message for this error (#1014)",
    # "stop bit received",
    # "internet is needed to catch the etherbunny",
    # "network down, IP packets delivered via UPS",
    # "Firmware update in the coffee machine",
    # "Temporal anomaly",
    # "Mouse has out-of-cheese-error",
    # "Borg implants are failing",
    # "Borg nanites have infested the server",
    # "error: one bad user found in front of screen",
    # "Please state the nature of the technical emergency",
    # "Internet shut down due to maintenance",
    # "Daemon escaped from pentagram",
    # "crop circles in the corn shell",
    # "sticky bit has come loose",
    # "Hot Java has gone cold",
    # "Cache miss - please take better aim next time",
    # "Hash table has woodworm",
    # "Trojan horse ran out of hay",
    # "Zombie processes detected, machine is haunted",
    # "overflow error in /dev/null",
    # "Browser's cookie is corrupted -- someone's been nibbling on it",
    # "Mailer-daemon is busy burning your message in hell",
    # "According to Microsoft, it's by design",
    # "vi needs to be upgraded to vii",
    # "greenpeace free'd the mallocs",
    # "Terrorists crashed an airplane into the server room, have to remove /bin/laden. (rm -rf /bin/laden)",
    # "astropneumatic oscillations in the water-cooling",
    # "Somebody ran the operating system through a spelling checker",
    # "Rhythmic variations in the voltage reaching the power supply",
    # "Keyboard Actuator Failure.  Order and Replace",
    # "Packet held up at customs",
    # "Propagation delay",
    # "High line impedance",
    # "Someone set us up the bomb",
    # "Power surges on the Underground",
    # "Don't worry; it's been deprecated. The new one is worse",
    # "Excess condensation in cloud network",
    # "It is a layer 8 problem",
    # "The math co-processor had an overflow error that leaked out and shorted the RAM",
    # "Leap second overloaded RHEL6 servers",
    # "DNS server drank too much and had a hiccup",
    # "Your machine had the fuses in backwards"
]


motivations = [
    "Next time you'll do better!",
    "Better luck next time!",
    "Don't be upset!",
    "Life goes on!",
    "Don't worry be happy."
]
