from xanmel.test.conftest import *

from xanmel.modules.xonotic.rcon_log import RconLogParser


@pytest.fixture
def log_parser(xon_module):
    return RconLogParser(xon_module.servers[0])


@pytest.fixture
def xon_server(xon_module, mocked_coro):
    srv = xon_module.servers[0]
    srv.update_server_stats_orig = srv.update_server_stats
    srv.update_server_stats = mocked_coro()
    return srv


@pytest.fixture
def example_scores():
    return b"""^7^xB50<E2><9D><87>^x4B0Skaven^xB50<E2><9D><87>^7^1 has been sublimated by ^7FPM^1's Vaporizer
:scores:dm_darkzone:317
:labels:player:score!!,,,,,,,,,,deaths<,dmg,dmgtaken<,,,,,,,,elo,,,,,,,,,,,,,,,,,kills,,,,,,,,,,,,,,suicides<,,,
:player:see-labels:30,0,0,0,0,0,0,0,0,0,32,3000,3200,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0:312:-1:4:FPM
:player:see-labels:21,0,0,0,0,0,0,0,0,0,17,2100,error,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0:185:-1:7:^x26FDarth Silvius^7
:player:see-labels:29,0,0,0,0,0,0,0,0,0,34,2900,435.384308,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0:309:-1:5:^xB50<E2><9D><87>^x4B0Skaven^xB50<E2><9D><87>^7
:end
:gameover
FPM ^7wins."""


@pytest.fixture
def example_teamscores():
    return b"""aoentuhantoehutnaoheu
:scores:tdm_stormkeep:85
:labels:player:score!!,kills,deaths<,suicides<,,,,,,
:player:see-labels:0,0,0,0,0,0,0,0,0,0:50:spectator:1:Trifluoperazine
:player:see-labels:-1,0,2,1,0,0,0,0,0,0:50:5:2:[BOT]Scorcher
:player:see-labels:2,2,0,0,0,0,0,0,0,0:50:14:3:[BOT]Hellfire
:player:see-labels:0,0,0,0,0,0,0,0,0,0:50:14:4:[BOT]Gator
:player:see-labels:0,0,1,0,0,0,0,0,0,0:50:5:5:[BOT]Necrotic
:labels:teamscores:score!!,
:teamscores:see-labels::1
:teamscores:see-labels::2
:teamscores:see-labels::3
:teamscores:see-labels::4
:teamscores:see-labels:-1,0:5
:teamscores:see-labels::6
:teamscores:see-labels::7
:teamscores:see-labels::8
:teamscores:see-labels::9
:teamscores:see-labels::10
:teamscores:see-labels::11
:teamscores:see-labels::12
:teamscores:see-labels::13
:teamscores:see-labels:2,0:14
:teamscores:see-labels::15
:end
:gameover
atoheuntahoetnuh
"""


@pytest.fixture
def example_scores_event():
    return {'players': [
        {'score': 30, 'deaths': 31, 'dmgtaken': 3100, 'dmg': 3380, 'team_id': -1, 'nickname': b'SummSumm', 'kills': 34,
         'number1': 1, 'elo': 0, 'suicides': 4},
        {'score': 0, 'deaths': 42, 'dmgtaken': 4200, 'dmg': 900, 'team_id': -1, 'nickname': b'ItzDub98', 'kills': 9,
         'number1': 4, 'elo': 0, 'suicides': 9}, {'score': 0, 'deaths': 6, 'dmgtaken': 600, 'dmg': 100, 'team_id': -1,
                                                  'nickname': b'^xF00\xee\x83\x88\xee\x83\x85\xee\x83\x81\xee\x83\x92\xee\x83\x94^x0EEof^xEF1\xee\x83\x87\xee\x83\x8f\xee\x83\x8c\xee\x83\x84^xFFF\xee\x82\xb5\xee\x82\xb2\xee\x82\xb3^7',
                                                  'kills': 1, 'number1': 6, 'elo': 0, 'suicides': 1}],
        'team_sort_column': 'score', 'map': 'revdm1', 'game_duration': 581, 'teams': [],
        'player_sort_column': 'score', 'gt': 'dm', 'team_header': None,
        'player_header': ['score', '', '', '', '', '', '', '', '', '', 'deaths', 'dmg', 'dmgtaken', '', '', '', '',
                          '', '', '', 'elo', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
                          'kills', '', '', '', '', '', '', '', '', '', '', '', '', '', 'suicides', '', '', '']}


@pytest.fixture
def example_team_scores_event():
    return {'players': [{'score': 5, 'deaths': 8, 'dmgtaken': 850, 'dmg': 1206, 'revivals': 0, 'team_id': 5,
                         'nickname': b'pip', 'kills': 13, 'number1': 6, 'elo': -2, 'suicides': 1},
                        {'score': 5, 'deaths': 6, 'dmgtaken': 600, 'dmg': 895, 'revivals': 2, 'team_id': 5,
                         'nickname': b'/^xF90\xe9\x82\xaa^xCCC/ C\xcc\xba\xcc\x9d\xcc\x9e\xcd\x96\xcc\xab\xcc\xbb\xcd\x85\xcd\x99\xcc\xb9\xcc\xb0\xcc\x9d\xcc\x9d\xcc\xb1\xcd\x8eo\xcd\x85\xcc\x9e\xcc\xad\xcc\xb0\xcd\x95\xcc\xa5\xcc\xaf\xcc\xb9\xcc\xba\xcd\x8e\xcc\xbb\xcc\xad\xcd\x8e\xcc\xb2\xcc\x9c\xcc\x9f\xcc\x9fr\xcc\xba\xcc\xa4\xcc\x9f\xcc\x9f\xcc\x96\xcd\x85\xcc\xa0\xcc\xbb\xcd\x88\xcc\x99\xcc\x9c\xcd\x87\xcc\x9f\xcc\x99o\xcc\xa0^xF90n^xFFFa^7',
                         'kills': 9, 'number1': 8,
                         'elo': 152.973511, 'suicides': 0},
                        {'score': 0, 'deaths': 10, 'dmgtaken': 1000, 'dmg': 1050, 'revivals': 0, 'team_id': 14,
                         'nickname': b'SummSumm', 'kills': 10, 'number1': 5, 'elo': 100, 'suicides': 0},
                        {'score': 0, 'deaths': 0, 'dmgtaken': 0, 'dmg': 0, 'revivals': 0, 'team_id': None,
                         'nickname': b'^1Tel^2etu^3bbi^6es^7', 'kills': 0,
                         'number1': 4, 'elo': 100, 'suicides': 0},
                        {'score': -8, 'deaths': 12, 'dmgtaken': 1101, 'dmg': 300, 'revivals':
                            0, 'team_id': 14, 'nickname': b'ItzDub98', 'kills': 3, 'number1': 7, 'elo': -2,
                         'suicides': 0}], 'team_sort_column': 'score', 'map': 'cucumber_v2', 'game_duration': 44,
            'teams': [{'score': 10, 'color': 1, 'team_id': 5}, {'score': 5, 'color': 4, 'team_id': 14}],
            'player_sort_column': 'score', 'gt': 'ft', 'team_header': ['score', ''],
            'player_header': ['score', '', '', '', '', '', '', '', '', '', 'deaths', 'dmg', 'dmgtaken', '', '', '', '',
                              '',
                              '', '', 'elo', '', '', 'revivals', '', '', '', '', '', '', '', '', '', '', '', '', '',
                              'kills', '', '', '', '',
                              '', '', '', '', '', '', '', '', '', 'suicides', '', '', '']}


@pytest.fixture
def example_server_stats():
    return {'recent_games': [{'epoch': 1482524915,
                              'fuzzy_dt': 'about 3 hours ago',
                              'game_id': 788160,
                              'game_type_cd': 'duel',
                              'map_id': 635,
                              'map_name': 'oilrig',
                              'player_id': 78802,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': '^x0BBS^x07BC^x05BR^x03BU^x20AF^x50AF^x80AY^7',
                              'winning_team': None},
                             {'epoch': 1482524230,
                              'fuzzy_dt': 'about 3 hours ago',
                              'game_id': 788155,
                              'game_type_cd': 'duel',
                              'map_id': 7523,
                              'map_name': 'cpm28',
                              'player_id': 78802,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': '^x0BBS^x07BC^x05BR^x03BU^x20AF^x50AF^x80AY^7',
                              'winning_team': None},
                             {'epoch': 1482523597,
                              'fuzzy_dt': 'about 3 hours ago',
                              'game_id': 788150,
                              'game_type_cd': 'dm',
                              'map_id': 14,
                              'map_name': 'atomforge',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482523264,
                              'fuzzy_dt': 'about 3 hours ago',
                              'game_id': 788148,
                              'game_type_cd': 'duel',
                              'map_id': 4,
                              'map_name': 'stormkeep',
                              'player_id': 78802,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': '^x0BBS^x07BC^x05BR^x03BU^x20AF^x50AF^x80AY^7',
                              'winning_team': None},
                             {'epoch': 1482522903,
                              'fuzzy_dt': 'about 3 hours ago',
                              'game_id': 788146,
                              'game_type_cd': 'dm',
                              'map_id': 3493,
                              'map_name': 'stormkeep-wreckage',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482522554,
                              'fuzzy_dt': 'about 3 hours ago',
                              'game_id': 788143,
                              'game_type_cd': 'duel',
                              'map_id': 495,
                              'map_name': 'solarium',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482522046,
                              'fuzzy_dt': 'about 3 hours ago',
                              'game_id': 788140,
                              'game_type_cd': 'duel',
                              'map_id': 3598,
                              'map_name': 'farewell_laserfun_TNG',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482521742,
                              'fuzzy_dt': 'about 4 hours ago',
                              'game_id': 788136,
                              'game_type_cd': 'duel',
                              'map_id': 4809,
                              'map_name': 'finalrage',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482521403,
                              'fuzzy_dt': 'about 4 hours ago',
                              'game_id': 788134,
                              'game_type_cd': 'dm',
                              'map_id': 3087,
                              'map_name': 'hub3aeroq3a_nex_r4_eac1',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482521208,
                              'fuzzy_dt': 'about 4 hours ago',
                              'game_id': 788131,
                              'game_type_cd': 'dm',
                              'map_id': 526,
                              'map_name': 'bio_labour',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482521097,
                              'fuzzy_dt': 'about 4 hours ago',
                              'game_id': 788130,
                              'game_type_cd': 'dm',
                              'map_id': 308,
                              'map_name': 'xoylent',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482520882,
                              'fuzzy_dt': 'about 4 hours ago',
                              'game_id': 788127,
                              'game_type_cd': 'dm',
                              'map_id': 8408,
                              'map_name': 'bgmp1',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482520641,
                              'fuzzy_dt': 'about 4 hours ago',
                              'game_id': 788124,
                              'game_type_cd': 'dm',
                              'map_id': 7752,
                              'map_name': 'cpm1a',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482520443,
                              'fuzzy_dt': 'about 4 hours ago',
                              'game_id': 788123,
                              'game_type_cd': 'dm',
                              'map_id': 4444,
                              'map_name': 'geit3dm5',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482520221,
                              'fuzzy_dt': 'about 4 hours ago',
                              'game_id': 788120,
                              'game_type_cd': 'dm',
                              'map_id': 4468,
                              'map_name': 'ql-aerospace',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482519179,
                              'fuzzy_dt': 'about 4 hours ago',
                              'game_id': 788109,
                              'game_type_cd': 'dm',
                              'map_id': 7497,
                              'map_name': 'alkdm11',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482518763,
                              'fuzzy_dt': 'about 4 hours ago',
                              'game_id': 788102,
                              'game_type_cd': 'dm',
                              'map_id': 4467,
                              'map_name': 'rota3dm3',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482518428,
                              'fuzzy_dt': 'about 4 hours ago',
                              'game_id': 788097,
                              'game_type_cd': 'dm',
                              'map_id': 903,
                              'map_name': 'asylum',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482518214,
                              'fuzzy_dt': 'about 5 hours ago',
                              'game_id': 788094,
                              'game_type_cd': 'dm',
                              'map_id': 521,
                              'map_name': 'campgrounds_beta4',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None},
                             {'epoch': 1482517970,
                              'fuzzy_dt': 'about 5 hours ago',
                              'game_id': 788089,
                              'game_type_cd': 'dm',
                              'map_id': 495,
                              'map_name': 'solarium',
                              'player_id': 2,
                              'server_id': 7975,
                              'server_name': 'exe.pub | Free for all Instagib | UK',
                              'winner': 'Anonymous Player',
                              'winning_team': None}],
            'server': {'ip_addr': '2001:41d0:2:5253::',
                       'location': None,
                       'name': 'exe.pub | Free for all Instagib | UK',
                       'server_id': 7975},
            'top_maps': {'server_id': '7975',
                         'top_maps': [{'map_id': 308,
                                       'map_name': 'xoylent',
                                       'rank': 1,
                                       'times_played': 10},
                                      {'map_id': 4512,
                                       'map_name': 'asylum_full',
                                       'rank': 2,
                                       'times_played': 9},
                                      {'map_id': 4809,
                                       'map_name': 'finalrage',
                                       'rank': 3,
                                       'times_played': 9},
                                      {'map_id': 450,
                                       'map_name': 'farewell_laserfun',
                                       'rank': 4,
                                       'times_played': 9},
                                      {'map_id': 617,
                                       'map_name': 'cube-arena',
                                       'rank': 5,
                                       'times_played': 9},
                                      {'map_id': 903,
                                       'map_name': 'asylum',
                                       'rank': 6,
                                       'times_played': 7},
                                      {'map_id': 3087,
                                       'map_name': 'hub3aeroq3a_nex_r4_eac1',
                                       'rank': 7,
                                       'times_played': 7},
                                      {'map_id': 4626,
                                       'map_name': 'zaxxonia_xon',
                                       'rank': 8,
                                       'times_played': 6},
                                      {'map_id': 865,
                                       'map_name': 'hellsgate',
                                       'rank': 9,
                                       'times_played': 6},
                                      {'map_id': 541,
                                       'map_name': 'warfare',
                                       'rank': 10,
                                       'times_played': 6}]},
            'top_players': {'server_id': '7975',
                            'top_players': [{'nick': 'ortanch',
                                             'player_id': 75186,
                                             'rank': 1,
                                             'time': 32401.0},
                                            {'nick': '^1|^2|^4| '
                                                     '^7k^xAAAo^x777u^x777g^x444i^1.exe '
                                                     '^x079\ud83c\udf0d^7',
                                             'player_id': 35182,
                                             'rank': 2,
                                             'time': 26867.0},
                                            {'nick': '^xF90sleet^7',
                                             'player_id': 82711,
                                             'rank': 3,
                                             'time': 26237.0},
                                            {'nick': '^x0BBS^x07BC^x05BR^x03BU^x20AF^x50AF^x80AY^7',
                                             'player_id': 78802,
                                             'rank': 4,
                                             'time': 24984.0},
                                            {'nick': '^xE20Tri^xF40flu^xFB0ope^xCB0raz^xAF1ine^7',
                                             'player_id': 75981,
                                             'rank': 5,
                                             'time': 19489.0},
                                            {'nick': 'andreymal',
                                             'player_id': 53317,
                                             'rank': 6,
                                             'time': 16073.0},
                                            {'nick': 'Anonymous Player #87310',
                                             'player_id': 87310,
                                             'rank': 7,
                                             'time': 14031.0},
                                            {'nick': 'dr. Equivalent',
                                             'player_id': 62153,
                                             'rank': 8,
                                             'time': 11596.0},
                                            {'nick': 'Anonymous Player #78998',
                                             'player_id': 78998,
                                             'rank': 9,
                                             'time': 11418.0},
                                            {'nick': 'FPM',
                                             'player_id': 85958,
                                             'rank': 10,
                                             'time': 11293.0}]},
            'top_scorers': {'server_id': '7975',
                            'top_scorers': [{'nick': '^1|^2|^4| '
                                                     '^7k^xAAAo^x777u^x777g^x444i^1.exe '
                                                     '^x079\ud83c\udf0d^7',
                                             'player_id': 35182,
                                             'rank': 1,
                                             'score': 4206},
                                            {'nick': '^x0BBS^x07BC^x05BR^x03BU^x20AF^x50AF^x80AY^7',
                                             'player_id': 78802,
                                             'rank': 2,
                                             'score': 2387},
                                            {'nick': '^xE20Tri^xF40flu^xFB0ope^xCB0raz^xAF1ine^7',
                                             'player_id': 75981,
                                             'rank': 3,
                                             'score': 2091},
                                            {'nick': 'ortanch',
                                             'player_id': 75186,
                                             'rank': 4,
                                             'score': 1949},
                                            {'nick': '^x6FF.^x111element^x6FF.^x111kwakk^x6FF!^x111e^x6FF.^7',
                                             'player_id': 39855,
                                             'rank': 5,
                                             'score': 1213},
                                            {'nick': '^xF90sleet^7',
                                             'player_id': 82711,
                                             'rank': 6,
                                             'score': 1158},
                                            {'nick': 'andreymal',
                                             'player_id': 53317,
                                             'rank': 7,
                                             'score': 1038},
                                            {'nick': 'FPM',
                                             'player_id': 85958,
                                             'rank': 8,
                                             'score': 969},
                                            {'nick': 'hop',
                                             'player_id': 83402,
                                             'rank': 9,
                                             'score': 848},
                                            {'nick': 'dem\ud83d\udc7dn',
                                             'player_id': 65399,
                                             'rank': 10,
                                             'score': 841}]}}
